on:
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string
      build_config:
        default: 'Release'
        type: string
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true

jobs:
  build-and-deploy:
    runs-on: [self-hosted, windows, dotnet]
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - run: dotnet restore ${{ inputs.project_path }}
      - run: dotnet build ${{ inputs.project_path }} -c ${{ inputs.build_config }} --no-restore
      - run: dotnet publish ${{ inputs.project_path }} -c ${{ inputs.build_config }} -o ./output --no-build
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app_name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./output
